### ISSUE TITLE
2.0.0 build failed with Kotlin 2.1.20

### ISSUE THREAD

**Issue by FlowFan** [InsertKoinIO/koin-annotations#251]
**Describe the bug**
After upgrading to Kotlin 2.1.20 and open ksp2, it build failed:
```
    Reason: Task ':composeApp:kspDebugKotlinAndroid' uses this output of task ':composeApp:kspCommonMainKotlinMetadata' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':composeApp:kspCommonMainKotlinMetadata' as an input of ':composeApp:kspDebugKotlinAndroid'.
      2. Declare an explicit dependency on ':composeApp:kspCommonMainKotlinMetadata' from ':composeApp:kspDebugKotlinAndroid' using Task#dependsOn.
      3. Declare an explicit dependency on ':composeApp:kspCommonMainKotlinMetadata' from ':composeApp:kspDebugKotlinAndroid' using Task#mustRunAfter.
```

**To Reproduce**
Modify the kotlin version to 2.1.20, open `ksp.useKSP2=true`, and then build

**Comment by Anthony17serrato** [comment]
Same problem for me, I have not been able to enable KSP2 on a KMP project

**Comment by arnaudgiuliani** [comment]
KSP2 mode is ok with 2.0.21. Official repo is using `ksp.useKSP2=true` perhaps there is something else

**Comment by FlowFan** [comment]
After removing the following code, it build success. But clean and rebuild will not find `org.koin.ksp.generated` code.
```
project.tasks.withType(KotlinCompilationTask::class.java).configureEach {
    if (name != "kspCommonMainKotlinMetadata") {
        dependsOn("kspCommonMainKotlinMetadata")
    }
}
```

**Comment by vinceglb** [comment]
Same here, I was not able to use KSP 2 with Koin annotations in a KMP project.

I created a new KMP project, and I setup only Koin and Koin Annotation following the documentation. The project works fine when I use KSP 1 (`2.1.20-1.0.32`) but I have a compilation error when upgrading to KSP 2 (`2.1.20-2.0.1`).

The compilation error is:

```
* What went wrong:
A problem was found with the configuration of task ':composeApp:kspCommonMainKotlinMetadata' (type 'KspAATask').
  - Gradle detected a problem with the following location: '<path>/Multiplatform-App/composeApp/build/generated/ksp/metadata/commonMain/kotlin'.
    
    Reason: Task ':composeApp:kspKotlinJvm' uses this output of task ':composeApp:kspCommonMainKotlinMetadata' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':composeApp:kspCommonMainKotlinMetadata' as an input of ':composeApp:kspKotlinJvm'.
      2. Declare an explicit dependency on ':composeApp:kspCommonMainKotlinMetadata' from ':composeApp:kspKotlinJvm' using Task#dependsOn.
      3. Declare an explicit dependency on ':composeApp:kspCommonMainKotlinMetadata' from ':composeApp:kspKotlinJvm' using Task#mustRunAfter.
```

You can find this project here: [repro.zip](https://github.com/user-attachments/files/20025370/repro.zip)

**Comment by joharei** [comment]
I fixed this by replacing OP's workaround with this:
```kt
tasks.withType<KspAATask>().configureEach {
    if (name != "kspCommonMainKotlinMetadata") {
        dependsOn("kspCommonMainKotlinMetadata")
    }
}
```

This seems to run the appropriate ksp tasks, but now my modules with `@ComponentScan` ignores definitions from other Gradle modules. This stopped working when updating from ksp 2.1.10-1.0.31 to 2.1.20-2.0.1.

**Comment by arnaudgiuliani** [comment]
Look at example-cmp, it can help you the setup: https://github.com/InsertKoinIO/koin-annotations/blob/main/example-cmp/composeApp/build.gradle.kts
