### ISSUE TITLE
Unreachable definition since 2.2.0

### ISSUE THREAD

**Issue by alexandre-thauvin** [InsertKoinIO/koin-annotations#336]
**Describe the bug**
I have a multi modular android project and after migrating from koin annotations bom 2.1.0 to 2.2.0 I started failing "unreachable definition" for a dependency of class.
Obviously the dependency in question is well defined via annotation.
Upgrading to version 2.3.1 doesnt fix the issue.

I did several back and forth from 2.3.1/2.2.0 to 2.1.0 and every time (including my jenkins pipeline) rollback to 2.1.0 fix the issue.

**To Reproduce**

**Expected behavior**
No compilation error

**Koin project used and used version (please complete the following information):**
koin bom version : 4.1.0
koin annotations bom: 2.3.1

**Additional moduleDefinition**
Ask if necessary

**Comment by arnaudgiuliani** [comment]
Can you test again your case with Koin Compiler 0.4.1 and Koin 4.2.0? Annotations stays the same, just KSP/Compiler changes. Please follow https://insert-koin.io/docs/migration/from-ksp-to-compiler-plugin

**Comment by alexandre-thauvin** [comment]
Testing - coming back to you soon @arnaudgiuliani

**Comment by arnaudgiuliani** [comment]
let's re-open if needed 👍
